modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/eatAWESOME/PixelmonSpawnAlerts/issues"
[[mods]]
modId="pixelmonspawnalerts"
version="1.0.4"
displayName="PixelmonSpawnAlerts"
logoFile="logo.png"
# credits=""
authors="Alden Tilley"
description='''
Improved alerts for Pixelmon spawning.
'''
[[dependencies.pixelmonspawnalerts]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixelmonspawnalerts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixelmonspawnalerts]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1,)"
    ordering="NONE"
    side="BOTH"